namespace ViolastroBot.DiscordServerConfiguration;

public static class Jokes
{
    public static List<string> List { get; } = new()
    {
        "Jur Loogman!",
        "I'm reading a book about anti-gravity. It's impossible to put down!",
        "Whaddya call someone with no body and no nose? Nobody knows! Bwehehe!",
        "Don't trust atoms. They make up everything!",
        "I used to have a job at a calendar factory, but I got the sack because I took a couple of days off!!",
        "Y'all know what the loudest pet you can get is? A trumpet!!",
        "Why did the scarecrow win an award? Because he was outstanding in his field!",
        "Why couldn't the bicycle stand up by itself? It was two tired!",
        "Did you hear about the restaurant on the moon? Great food, no atmosphere!",
        "I'm finna run out of jokes soon!",
        "Did you hear the rumor about butter? Well, I'm not going to spread it!",
        "Why do you never see elephants hiding in trees? Because they're so good at it!",
        "How does a penguin build its house? Igloos it together!",
        "Why don't skeletons ever go trick or treating? Because they have no body to go with!",
        "Why did the old man fall in the well? Because he couldn't see that well!",
        "Why did the invisible man turn down the job offer? He couldn't see himself doing it!",
        "I'm so good at sleeping I can do it with my eyes closed!",
        "I thought about going on an all-almond diet… But that's just nuts!",
        "I would avoid the sushi if I was you. It's a little fishy!",
        "<https://www.roblox.com/games/433264537/DISCONTINUED-READ-DESC-Vibrant-Venture-v1-4-1>",
        "Two goldfish are in a tank. One says to the other, 'Do you know how to drive this thing?'",
        "Did you hear about the Italian chef who died? He pasta way!",
        "No! I'm busy conquering the world!",
        "What's orange and sounds like a parrot? A carrot!",
        "2020!",
        "What's a ninja's favorite type of shoes? Sneakers!",
        "https://smurfs.fandom.com/wiki/Death",
        "Why do cows wear bells? Because their horns don't work!",
        "I tried to catch some fog yesterday. Mist!",
        "Why don’t eggs tell jokes? They!d crack each other up!",
        "Why was the math book sad? It had too many problems!",
        "Why don't some couples go to the gym? Because some relationships don't work out!",
        "I stayed up all night wondering where the sun went... then it dawned on me!",
        "What do you call fake spaghetti? An impasta!",
        "My plants are having a party. I hope they don't soil themselves!",
        "Why can't your nose be 12 inches long? Because then it'd be a foot!",
        "What do you call a group of musical whales? An orca-stra!",
        "Why did the coffee file a police report? It got mugged!",
        "What do you call cheese that isn't yours? Nacho cheese!",
        "Why did the golfer bring two pairs of pants? In case he got a hole in one!",
        "Did you hear about the kidnapping at school? It's all good, he woke up!",
        "Why don't oysters donate to charity? Because they're shellfish!",
        "How do you organize a space party? You planet!",
        "I used to hate facial hair... but then it grew on me!",
    };
}